export const Book = {
    allowAnonLogging: null,
    authors: null,
    averageRating: null,
    canonicalVolumeLink: null,
    categories: null,
    contentVersion: null,
    description: null,
    id: null,
    imageLinks: null,
    industryIdentifiers: null,
    infoLink: null,
    language: null,
    maturityRating: null,
    pageCount: null,
    panelizationSummary: null,
    previewLink: null,
    printType: null,
    publishedDate: null,
    publisher: null,
    ratingsCount: null,
    readingModes: null,
    shelf: null,
    subtitle: null,
    title: null
}